cat ../../*/data/*.plasmid_list.xls > ALL.plasmid_list.xls
cat ../../*/data/*.ARG_list.xls > ALL.ARG_list.xls
cat ../../*/data/*.CRISPR-Cas_list.xls > ALL.CRISPR-Cas_list.xls
cat ../../*/data/*.protein_list.xls > ALL.protein_list.xls
cat ../../*/data/*.SMs_list.xls > ALL.SMs_list.xls
cat ../../*/data/*.SP_list.xls > ALL.SP_list.xls
cat ../../*/data/*.TMHs_list.xls > ALL.TMHs_list.xls
cat ../../*/data/*.trna_list.xls > ALL.trna_list.xls
cat ../../*/data/*.VF_list.xls > ALL.VF_list.xls