# Generated by Django 3.2.12 on 2024-05-13 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='antimicrobialresistancegene',
            name='drug_class',
            field=models.TextField(blank=True, null=True),
        ),
    ]
