# Generated by Django 3.2.12 on 2024-05-13 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0002_alter_antimicrobialresistancegene_drug_class'),
    ]

    operations = [
        migrations.AlterField(
            model_name='antimicrobialresistancegene',
            name='antibiotic',
            field=models.TextField(blank=True, null=True),
        ),
    ]
