# Generated by Django 3.2.12 on 2024-05-13 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0003_alter_antimicrobialresistancegene_antibiotic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='antimicrobialresistancegene',
            name='amr_gene_family',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='antimicrobialresistancegene',
            name='resistance_mechanism',
            field=models.TextField(blank=True, null=True),
        ),
    ]
