# Generated by Django 3.2.12 on 2024-05-15 01:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0004_auto_20240513_1737'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transmembranehelices',
            name='position',
        ),
        migrations.RemoveField(
            model_name='transmembranehelices',
            name='self_end',
        ),
        migrations.RemoveField(
            model_name='transmembranehelices',
            name='self_start',
        ),
        migrations.CreateModel(
            name='Helices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(blank=True, max_length=200, null=True)),
                ('self_start', models.IntegerField(blank=True, null=True)),
                ('self_end', models.IntegerField(blank=True, null=True)),
                ('tmh', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='helices', to='database.transmembranehelices')),
            ],
        ),
    ]
