# Generated by Django 4.2.1 on 2024-06-26 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("database", "0008_remove_antimicrobialresistancegene_plasmid_and_more")
    ]

    operations = [
        migrations.AddField(
            model_name="antimicrobialresistancegene",
            name="source",
            field=models.IntegerField(
                choices=[
                    (0, "PLSDB"),
                    (1, "IMG-PR"),
                    (2, "COMPASS"),
                    (3, "GenBank"),
                    (4, "RefSeq"),
                    (5, "EMBL"),
                    (6, "Kraken2"),
                    (7, "DDBJ"),
                    (8, "TPA"),
                ],
                default=0,
            ),
        ),
        migrations.AddField(
            model_name="crispr",
            name="source",
            field=models.IntegerField(
                choices=[
                    (0, "PLSDB"),
                    (1, "IMG-PR"),
                    (2, "COMPASS"),
                    (3, "GenBank"),
                    (4, "RefSeq"),
                    (5, "EMBL"),
                    (6, "Kraken2"),
                    (7, "DDBJ"),
                    (8, "TPA"),
                ],
                default=0,
            ),
        ),
        migrations.AddField(
            model_name="host",
            name="source",
            field=models.IntegerField(
                choices=[
                    (0, "PLSDB"),
                    (1, "IMG-PR"),
                    (2, "COMPASS"),
                    (3, "GenBank"),
                    (4, "RefSeq"),
                    (5, "EMBL"),
                    (6, "Kraken2"),
                    (7, "DDBJ"),
                    (8, "TPA"),
                ],
                default=0,
            ),
        ),
        migrations.AddField(
            model_name="protein",
            name="source",
            field=models.IntegerField(
                choices=[
                    (0, "PLSDB"),
                    (1, "IMG-PR"),
                    (2, "COMPASS"),
                    (3, "GenBank"),
                    (4, "RefSeq"),
                    (5, "EMBL"),
                    (6, "Kraken2"),
                    (7, "DDBJ"),
                    (8, "TPA"),
                ],
                default=0,
            ),
        ),
        migrations.AddField(
            model_name="secondarymetabolism",
            name="source",
            field=models.IntegerField(
                choices=[
                    (0, "PLSDB"),
                    (1, "IMG-PR"),
                    (2, "COMPASS"),
                    (3, "GenBank"),
                    (4, "RefSeq"),
                    (5, "EMBL"),
                    (6, "Kraken2"),
                    (7, "DDBJ"),
                    (8, "TPA"),
                ],
                default=0,
            ),
        ),
        migrations.AddField(
            model_name="signalpeptides",
            name="source",
            field=models.IntegerField(
                choices=[
                    (0, "PLSDB"),
                    (1, "IMG-PR"),
                    (2, "COMPASS"),
                    (3, "GenBank"),
                    (4, "RefSeq"),
                    (5, "EMBL"),
                    (6, "Kraken2"),
                    (7, "DDBJ"),
                    (8, "TPA"),
                ],
                default=0,
            ),
        ),
        migrations.AddField(
            model_name="trna",
            name="source",
            field=models.IntegerField(
                choices=[
                    (0, "PLSDB"),
                    (1, "IMG-PR"),
                    (2, "COMPASS"),
                    (3, "GenBank"),
                    (4, "RefSeq"),
                    (5, "EMBL"),
                    (6, "Kraken2"),
                    (7, "DDBJ"),
                    (8, "TPA"),
                ],
                default=0,
            ),
        ),
        migrations.AddField(
            model_name="virulentfactor",
            name="source",
            field=models.IntegerField(
                choices=[
                    (0, "PLSDB"),
                    (1, "IMG-PR"),
                    (2, "COMPASS"),
                    (3, "GenBank"),
                    (4, "RefSeq"),
                    (5, "EMBL"),
                    (6, "Kraken2"),
                    (7, "DDBJ"),
                    (8, "TPA"),
                ],
                default=0,
            ),
        ),
    ]
