# Generated by Django 4.2.1 on 2024-06-26 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("database", "0011_alter_plasmid_plasmid_id")]

    operations = [
        migrations.AlterField(
            model_name="plasmid",
            name="plasmid_id",
            field=models.CharField(max_length=200),
        )
    ]
