# Generated by Django 4.2.1 on 2024-06-29 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("database", "0014_alter_protein_cog_category_alter_protein_cog_id_and_more")
    ]

    operations = [
        migrations.AlterField(
            model_name="antimicrobialresistancegene",
            name="best_hit_aro",
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name="antimicrobialresistancegene",
            name="cutoff",
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name="antimicrobialresistancegene",
            name="hsp_identifier",
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name="antimicrobialresistancegene",
            name="orf_source",
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name="antimicrobialresistancegene",
            name="plasmid_id",
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name="antimicrobialresistancegene",
            name="product",
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name="antimicrobialresistancegene",
            name="protein_id",
            field=models.CharField(max_length=1000),
        ),
    ]
