# Generated by Django 4.2.1 on 2024-06-29 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("database", "0015_alter_antimicrobialresistancegene_best_hit_aro_and_more")
    ]

    operations = [
        migrations.AlterField(
            model_name="signalpeptides",
            name="cs_position",
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name="signalpeptides",
            name="prediction",
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name="signalpeptides",
            name="product",
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name="signalpeptides",
            name="protein_id",
            field=models.CharField(max_length=1000),
        ),
    ]
