# Generated by Django 4.2.1 on 2024-09-10 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("database", "0017_alter_antimicrobialresistancegene_source_and_more")
    ]

    operations = [
        migrations.AddField(
            model_name="plasmid",
            name="unique_id",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="antimicrobialresistancegene",
            name="plasmid_id",
            field=models.CharField(
                blank=True, db_index=True, max_length=1000, null=True
            ),
        ),
        migrations.AlterField(
            model_name="crispr",
            name="plasmid_id",
            field=models.CharField(
                blank=True, db_index=True, max_length=200, null=True
            ),
        ),
        migrations.AlterField(
            model_name="host",
            name="plasmid_id",
            field=models.CharField(
                blank=True, db_index=True, max_length=200, null=True
            ),
        ),
        migrations.AlterField(
            model_name="plasmid",
            name="plasmid_id",
            field=models.CharField(db_index=True, max_length=200),
        ),
        migrations.AlterField(
            model_name="protein",
            name="plasmid_id",
            field=models.CharField(
                blank=True, db_index=True, max_length=1000, null=True
            ),
        ),
        migrations.AlterField(
            model_name="secondarymetabolism",
            name="plasmid_id",
            field=models.CharField(
                blank=True, db_index=True, max_length=200, null=True
            ),
        ),
        migrations.AlterField(
            model_name="signalpeptides",
            name="plasmid_id",
            field=models.CharField(
                blank=True, db_index=True, max_length=200, null=True
            ),
        ),
        migrations.AlterField(
            model_name="transmembranehelices",
            name="plasmid_id",
            field=models.CharField(
                blank=True, db_index=True, max_length=200, null=True
            ),
        ),
        migrations.AlterField(
            model_name="trna",
            name="plasmid_id",
            field=models.CharField(
                blank=True, db_index=True, max_length=200, null=True
            ),
        ),
        migrations.AlterField(
            model_name="virulentfactor",
            name="plasmid_id",
            field=models.CharField(
                blank=True, db_index=True, max_length=200, null=True
            ),
        ),
    ]
