# Generated by Django 4.2.1 on 2024-09-15 21:29

from django.db import migrations, models

def convert_integer_to_char(apps, schema_editor):
    MyModel = apps.get_model('database', 'Plasmid')
    for obj in MyModel.objects.all():
        obj.source = str(obj.source)
        obj.save()

class Migration(migrations.Migration):

    dependencies = [("database", "0020_allplasmid")]

    operations = [
        # migrations.AlterField(
        #     model_name="plasmid",
        #     name="source",
        #     field=models.CharField(blank=True, max_length=200, null=True),
        # )
        migrations.RunPython(convert_integer_to_char),
    ]
