# Generated by Django 4.2.1 on 2024-09-15 22:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("database", "0022_auto_20240915_2149")]

    operations = [migrations.RemoveField(model_name="allplasmid", name="unique_id")]
