# Generated by Django 4.2.1 on 2024-09-28 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("database", "0023_remove_allplasmid_unique_id")]

    operations = [
        migrations.AlterField(
            model_name="allplasmid",
            name="plasmid_id",
            field=models.TextField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name="allplasmid",
            name="source",
            field=models.TextField(blank=True, null=True),
        ),
    ]
