# Generated by Django 4.2.1 on 2024-09-28 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("database", "0024_alter_allplasmid_plasmid_id_alter_allplasmid_source")
    ]

    operations = [
        migrations.AlterField(
            model_name="allplasmid",
            name="plasmid_id",
            field=models.TextField(blank=True, null=True),
        )
    ]
